const constants ={
  "User_exists": "User already exist.",
  "Data_retrieved" :"Data successfully retrieved",
  "Data_created" :"User Profile was created successfully!",
  "Data_updated":"User Profile was update successfully!",
  "Data_Deleted" :"User profile was deleted successfully!",
  "Data_not_updated":"Id may be missing user profile not updated",
  "Data_not_updated_error":"Data not updated, Some error occurred!",
  "Data_not_deleted":"Id may be missing user data not deleted",
  "Data_not_deleted_error":"User data not deleted, Some error occurred!",
  "Some_error":"Some error occurred!",
  "User_not_exists":"No such user Found.",
  "Class_not_exists":"No such class found.",
  "Not_valid_Password" :"Please enter the valid password",
  "Logged_in": "Successfully logged in.",
  "invalid_user": "Invalid user, Please relogin.",
  "Not_valid_Otp": "Incorrect OTP. Pleases check the OTP.",
  "OTP_Sent": "OTP sent Successfully",
  "Inactive_User" : "Inactive User" ,
  "Email_Verifyed" : "Email Verifyed",
  "SOMETHING_WRONG": "Something went wrong, Please try again.",
  "INVALID_PROFILE_PHOTO" : "Invalid profile photo",
  "INVALID_USER" : "Invalid user",
  "SUCCESS" : "Success",
  "CHANGED_PASSWORD" : "Password changed successfully",
  "CATEGORY_CREATED" : "Category created successfully",
  "INVALID_TITLE_OR_TYPE" : "Invalid title or type, please try again.",
  "CATEGORY_UPDATED": "Category updated successfully",
  "CATEGORY_NOT_EXIST" : "Category not exist",
  "SUBJECT_CREATED" : "Subject created succesfully",
  "SUBJECT_UPDATED": "Subject updated successfully",
  "SUBJECT_NOT_EXIST" : "Subject not exist",
  "CONTENT_CREATED" : "Content created succesfully",
  "CONTENT_UPDATED": "Content updated successfully",
  "CONTENT_NOT_EXIST" : "Content not exist",
  "INVALID_INPUT" : "Invalid input",
  "USER_UPDATED" : "User updated succesfully",
  "PLAYLIST_CREATED" : "Playlist created succesfully",
  "PLAYLIST_UPDATED": "Playlist updated successfully",
  "PLAYLIST_NOT_EXIST" : "Playlist not exist",
  "MODULE_CREATED" : "Module created succesfully",
  "MODULE_UPDATED": "Module updated successfully",
  "MODULE_NOT_EXIST" : "Module not exist",
  "LOGOUT_SUCCESS" : "Logout successful.",
  "INACTIVE_STATUS" : "Your account has been locked, please contact the admin.",
  "INCORRECT_PASSWORD" : "Your password is incorrect.",
  "PASSWORD_NOT_MATCHED" : "Password not matched.",
  "USER_NOT_EXIST" : "User not exist.",
  "OTP_NOT_VERIFYED" : "OTP not verifyed",
  "OTP_EXPIRED" : "Otp expired, Please resent it",
  "CATEGORY_CANT_DELETE" : "Category can't delete, because it's accociated with subject.",
  "CATEGORY_CANT_DELETE_CONTENT" : "Category can't delete, because it's accociated with content.",
  "INVALID_PLAYLIST" : "Invalid playlist",
  "ALREADY_ENROLLED" : "User already enrolled in this playlist",
  "PLAYLIST_NOT_EXIST" : "Invalid playlist id",
  "PLAYLIST_NOT_AVAILABLE" : "Play list not available",
  "PLAY_LIST_MODULE_CONTENT_CREATED" : "Playlist module content created succesfully",
  "PLAY_LIST_MODULE_CONTENT_DELETE_ERROR" : "module is associated with the content",
}

module.exports={constants}
